declare function route(name: string, params?: Record<string, any>): string;
declare function route(name: string, params?: Record<string, any>): {
    toString(): string;
    get url(): string;
    get params(): Record<string, any>;
    get ziggy(): Record<string, any>;
    has(name: string): boolean;
    current(name?: string, params?: Record<string, any>): boolean;
    get query(): Record<string, any>;
    get defaults(): Record<string, any>;
    get defined(): boolean;
    get name(): string;
    get path(): string;
    get domain(): string;
    get port(): string;
    get protocol(): string;
    get host(): string;
    get origin(): string;
    get baseUrl(): string;
    get urlWithQuery(): string;
    get urlWithoutQuery(): string;
    get urlWithParams(): string;
    get urlWithoutParams(): string;
    get urlWithQueryAndParams(): string;
    get urlWithoutQueryAndParams(): string;
    get urlWithQueryString(): string;
    get urlWithoutQueryString(): string;
    get urlWithHash(): string;
    get urlWithoutHash(): string;
    get urlWithHashAndQuery(): string;
    get urlWithoutHashAndQuery(): string;
    get urlWithHashAndParams(): string;
    get urlWithoutHashAndParams(): string;
    get urlWithHashAndQueryAndParams(): string;
    get urlWithoutHashAndQueryAndParams(): string;
};
